Support var in gnome-sdk-build

diff --git a/gnome-sdk-build b/gnome-sdk-build
--- a/gnome-sdk-build
+++ b/gnome-sdk-build
@@ -23,6 +23,7 @@ Runs a command in the gnome sdk runtime.
     -b, --branch    run with a specific runtime branch
     -t, --target    run with the specified build dir in /self
     -c, --clear     clear the build dir before starting
+    -v, --var       init /var from clean runtime Var companion
 
 All runtimes are stored in ${XDK_DATA_HOME}.
 The default sdk is called 'org.gnome.Sdk' and can be changed by setting GNOME_SDK_RUNTIME.
@@ -40,6 +41,7 @@ TARGET=${GNOME_SDK_TARGET:-default}
 RUNTIME=${GNOME_SDK_RUNTIME:-org.gnome.Sdk}
 BRANCH=${GNOME_SDK_RUNTIME_BRANCH:-3.14}
 CLEAR=no
+VAR=no
 
 while :; do
     case $1 in
@@ -80,6 +82,9 @@ while :; do
         -c|--clear)
             CLEAR=yes
             ;;
+        -v|--var)
+            VAR=yes
+            ;;
         --)
             shift
             break
@@ -104,6 +109,7 @@ declare -x PKG_CONFIG_PATH="/self/lib/pkgconfig:/self/share/pkgconfig"
 mkdir -p $BUILD
 
 RUNTIME_DIR=$DEPLOY/runtime/$RUNTIME/$ARCH/$BRANCH/deploy/latest/files
+VAR_DIR=$DEPLOY/runtime/${RUNTIME}Var/$ARCH/$BRANCH/deploy/latest/files
 
 if ! test -d $RUNTIME_DIR; then
     echo "Error: Runtime '$RUNTIME' does not exist at $RUNTIME_DIR"
@@ -116,5 +122,18 @@ if [ $CLEAR != "no" ]; then
 fi
 mkdir -p $APP_DIR/var
 mkdir -p $APP_DIR/files
+
+    set -x
+
+if [ $VAR != "no" ]; then
+
+    if ! test -d $VAR_DIR; then
+        echo "Error: Runtime '${RUNTIME}Var' does not exist at $VAR_DIR"
+        exit 1
+    fi
+
+    rm -rf $APP_DIR/var
+    cp -a -T  $VAR_DIR $APP_DIR/var
+fi
 
 gnome-sdk-helper -w -a $APP_DIR/files -v $APP_DIR/var $RUNTIME_DIR "$@"
